name: "Installer"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the installer"
        required: true
        default: "0.0.0"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
            **/target
          key: ${{ runner.os }}-pnpm-rust-${{ hashFiles('**/pnpm-lock.yaml', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-rust-
      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install frontend Dependencies
        run: |
          pnpm install --filter=installer --frozen-lockfile --prefer-offline
      - name: Build Installer
        env:
          VITE_HF_TOKEN: ${{ secrets.VITE_HF_TOKEN }}
        run: pnpm installer tauri build
      - name: Rename Installer
        run: |
          Rename-Item -Path "D:\\a\\Applio-App\\Applio-App\\apps\\installer\\src-tauri\\target\\release\installer-applio-app.exe" -NewName "Applio-App-Installer.exe"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            D:\\a\\Applio-App\\Applio-App\\apps\\installer\\src-tauri\\target\\release\Applio-App-Installer.exe
          tag_name: installer-${{ github.event.inputs.version }}
          name: Installer ${{ github.event.inputs.version }}
          prerelease: true
          generate_release_notes: true
          body: |
            Windows installer for Applio App version ${{ github.event.inputs.version }}
  
  upload_release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get the latest release info
        id: release
        run: |
          release_info=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "Release info: $release_info"
          echo "RELEASE_NAME=$(echo $release_info | jq -r '.name')" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(echo $release_info | jq -r '.tag_name')" >> $GITHUB_ENV
          echo "RELEASE_URL=$(echo $release_info | jq -r '.html_url')" >> $GITHUB_ENV
          echo "ASSET_URL=$(echo $release_info | jq -r '.assets[0].browser_download_url')" >> $GITHUB_ENV

      - name: Upload to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            A new release has been published!
            **Name**: ${{ env.RELEASE_NAME }}
            **Tag**: ${{ env.RELEASE_TAG }}
            [Release Link](${{ env.RELEASE_URL }})
          file: ${{ env.ASSET_URL }}
