name: Installer
on: workflow_dispatch 

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--no-bundle'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # Set this to npm, yarn or pnpm.

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable 

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install --filter=installer

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./apps/installer
          tagName: installer-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'Installer v__VERSION__'
          releaseBody: '## How to update? 1. Delete the current Applio App folder from your system. 2. Run the installer again to complete the update.'
          releaseDraft: true
          prerelease: true
          args: ${{ matrix.args }}
